### ISSUE TITLE
Task: Fine-tuning Object detection

### ISSUE THREAD

**Issue by Anindyadeep** [shreydan/computer-vision-course#10]
## Objective

This issue is about the task  Vision transformer: Fine-tuning:  Object Detection . 

### Sub-tasks

- [ ] Add the jupyter notebook of the model
- [ ] mdx file about object detection (although this should be explained in another chapter , i am adding for example)
- [X] pick a dataset and describe
- [ ] pick a model, explain intuition
- [ ] add the architecture graph for the model
- [ ] add some common repositories for the model
- [ ] add codeblock (import from huggingface hub ) about transfer learning with the model on the dataset

### Definition of Done

- [ ] When all of the sub-tasks are done.
