### ISSUE TITLE
Task : Transfer Learning Segmentation

### ISSUE THREAD

**Issue by hanouticelina** [shreydan/computer-vision-course#6]
# Plan 
This is my setup for transfer learning on segmentation task:

- **model**: I suggest using [facebook/maskformer-swin-base-ade](https://huggingface.co/facebook/maskformer-swin-base-ade) trained on ADE20k with a swin transformer backbone. Since the model can be used for both semantic, and panoptic segmentation, I'm planning to illustrate the 2 types of segmentations on one example.  

- **dataset**: For the dataset, [Sidewalk Semantic](https://huggingface.co/datasets/segments/sidewalk-semantic)   might be a good choice, the dataset is relatively small with a 1000 images among 34 categories. 

In the notebook, I will first show how to do inference using the model on one example and then I will proceed with freezing every layer of the backbone and the pixel decoder and train the transformer module, the class predictor and the mask embedder(see : [MaskFormerForInstanceSegmentation](https://github.com/huggingface/transformers/blob/main/src/transformers/models/maskformer/modeling_maskformer.py#L1700)).  

I will try to use HF ecosystem (transformers, datasets, evaluate) as much as possible. 

For the the .mdx, the idea is to explain briefly the three types of segmentation, what transfer learning implies when using transformer-based segmentation models (ie [SegFormer](https://huggingface.co/docs/transformers/main/en/model_doc/segformer#overview), [MaskFormer](https://huggingface.co/docs/transformers/main/en/model_doc/maskformer#overview), [Mask2Former](https://huggingface.co/docs/transformers/main/en/model_doc/mask2former#overview) etc..). I will detail more the plan later. 

# Tasks 
- [x] Pick a dataset.
- [x] Pick a model.
- [x] Add the notebook containing : loading of the dataset, showing the differences between the 2 types of segmentation, showing recipe/sanity checks when training a segmentation model, training (with transfer learning) the chosen model. 
- [x] Explain the architecture, the approach behind transfer learning on these kind of models and the metric used in the notebook.
- [ ] write mdx about ViT for segmentation and transfer learning.
