### ISSUE TITLE
Task: Object Detection

### ISSUE THREAD

**Issue by sezan92** [shreydan/computer-vision-course#8]
## Objective

This issue is about the task  Vision transformer: Transfer learning:  Object Detection . 

### Sub-tasks

- [ ] mdx file about object detection (although this should be explained in another chapter , i am adding for example)
- [ ] pick a dataset and describe
- [ ] pick a model, explain intuition
- [ ] add the architecture graph for the model
- [ ] add some common repositories for the model
- [ ] add codeblock (import from huggingface hub ) about transfer learning with the model on the dataset

### Definition of Done

- [x] When all of the sub-tasks are done.
